name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: editor/package-lock.json
      - run: npm ci --prefix editor
      - run: npm test --prefix editor
      - run: npm run build --prefix editor
      # Upload static build to Pages using v4 to avoid deprecated artifact action
      - uses: actions/upload-pages-artifact@v4
        with:
          path: editor/dist

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
